// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TallerDeBicicletasPro.Persistence.Context;

#nullable disable

namespace TallerDeBicicletasPro.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251209130545_1")]
    partial class _1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TallerDeBicicletasPro.Domain.Entities.Bicicleta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Año")
                        .HasColumnType("int");

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("Bicicletas", (string)null);
                });

            modelBuilder.Entity("TallerDeBicicletasPro.Domain.Entities.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Clientes", (string)null);
                });

            modelBuilder.Entity("TallerDeBicicletasPro.Domain.Entities.Mecanico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Especialidad")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Mecanicos", (string)null);
                });

            modelBuilder.Entity("TallerDeBicicletasPro.Domain.Entities.Reparacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BicicletaId")
                        .HasColumnType("int");

                    b.Property<decimal>("Costo")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("MecanicoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BicicletaId");

                    b.HasIndex("MecanicoId");

                    b.ToTable("Reparaciones", (string)null);
                });

            modelBuilder.Entity("TallerDeBicicletasPro.Domain.Entities.Bicicleta", b =>
                {
                    b.HasOne("TallerDeBicicletasPro.Domain.Entities.Cliente", "Cliente")
                        .WithMany("Bicicletas")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("TallerDeBicicletasPro.Domain.Entities.Reparacion", b =>
                {
                    b.HasOne("TallerDeBicicletasPro.Domain.Entities.Bicicleta", "Bicicleta")
                        .WithMany("Reparaciones")
                        .HasForeignKey("BicicletaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TallerDeBicicletasPro.Domain.Entities.Mecanico", "Mecanico")
                        .WithMany("Reparaciones")
                        .HasForeignKey("MecanicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bicicleta");

                    b.Navigation("Mecanico");
                });

            modelBuilder.Entity("TallerDeBicicletasPro.Domain.Entities.Bicicleta", b =>
                {
                    b.Navigation("Reparaciones");
                });

            modelBuilder.Entity("TallerDeBicicletasPro.Domain.Entities.Cliente", b =>
                {
                    b.Navigation("Bicicletas");
                });

            modelBuilder.Entity("TallerDeBicicletasPro.Domain.Entities.Mecanico", b =>
                {
                    b.Navigation("Reparaciones");
                });
#pragma warning restore 612, 618
        }
    }
}
